function createfigure(YMatrix1)
%CREATEFIGURE(YMatrix1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 16-Nov-2021 11:38:55

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'LineWidth',2);
set(plot1(1),'DisplayName','Setpoint');
set(plot1(2),'DisplayName','Position');

% Create ylabel
ylabel({'Setpoint'});

% Create xlabel
xlabel({'Time'});

% Create title
title('PID Tuning 1, Kp = 1, Ki = 0, Kd = 0','BackgroundColor',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 1000]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 600]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontWeight','bold','XGrid','on','YGrid','on');
% Create legend
legend(axes1,'show');

